---
- name: Enable COPR repository for ghostty
  become: true
  ansible.builtin.command: dnf copr enable scottames/ghostty -y
  changed_when: false

- name: Install ghostty
  become: true
  ansible.builtin.dnf:
    name: ghostty
    state: present

- name: Create the '$HOME/.config/ghostty' directory if not exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/ghostty"
    mode: "0755"
    state: directory

- name: Create symlink of files to '$HOME/.config/ghostty' directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_facts['user_dir'] }}/.config/ghostty/{{ item }}"
    state: link
    force: true
  with_items:
    - config
